### ISSUE TITLE
Support for FastAPI docs

### ISSUE THREAD

**Issue by gospodima** [frankie567/starlette-csrf#19]
Hi,

README mentions on how to use CSRFMiddleware with FastAPI. Is there any option to integrate it into FastAPI's [docs](https://fastapi.tiangolo.com/features/#automatic-docs) system? I am trying to implement cookie-based jwt approach similar to [this](https://fastapitutorial.medium.com/fastapi-securing-jwt-token-with-httponly-cookie-47e0139b8dde) one, which doesn't differ much from FastAPI's documentation [approach](https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/), besides using jwt token via cookie essentially.

However, authorize option won't send csrf header automatically. Is there any option to adjust this?

**Comment by frankie567** [comment]
Unfortunately, no. Since this is implemented as a middleware, there is no way to hook into the OpenAPI/Swagger generation logic in FastAPI.

I'm not even sure anyway Swagger is able to support CSRF transparently.
